SYSTEM:
  ETE_LATENCY_THRESHOLD: 5
  #DATA_DIR: 'C:\Users\Alisson Cds\OneDrive\Desktop\vr_streaming\data_sets\'
  DATA_DIR: '/Users/alisson-cds/Desktop/vr_streaming/data_sets/'
  BS_FILE: 'base_stations.json'
  MEC_FILE: 'mecs.json'
  HMDS_FILE: 'hmds.json'
  #RESULTS_DIR: '/home/ubuntu/scg/results/'
  #SERVICE_PER_USER: Bern -> 10, 20, 30 | Geneva -> 25, 35, 45 | Zurich -> 50, 55, 60

# variables for mininet-wifi 
NETWORK:
  HMDS: 50
  HMD_RANGE: 0.05
  SERVICE_PER_HMD: 1
  BASE_STATIONS: 100
  BASE_STATION_RANGE: 0.13
  NETWORK_FILE: base_stations.json
  #NETWORK_FILE_DIR: C:\Users\Alisson Cds\OneDrive\Desktop\vr_streaming\data_sets\ 
  #NETWORK_FILE: network.json
  #NETWORK_FILE_DIR: C:\Users\Alisson Cds\OneDrive\Desktop\vr_streaming\utils\network\network_topologies\ 
  #NETWORK_FILE_DIR: /Users/alisson-cds/Desktop/vr_streaming/utils/network/network_topologies/
  NETWORK_FILE_DIR: /Users/alisson-cds/Desktop/vr_streaming/data_sets/
  #NET_GRAPH_DIMENSION: 2000
  #HMD_MIN_VELOCITY: 1000
  #HMD_MAX_VELOCITY: 1500
  #BS_CHANNEL: 1
  #BS_RANGE: 500
  #BS_MODE: 'g'
  #BS_TX_POWER: 76
  #LOWER_LATENCY_THRESHOLD: 0.5 
  #UPPER_LATENCY_THRESHOLD: 1   

MIGRATION:  
  ALGORITHMS: 5
  SCG:
    LATENCY_CHECK: False

MEC_SERVERS:
  GPU_LAM: 110
  CPU_LAM: 200
  OVERALL_MECS: 100
  MECS_WITHOUT_GPUS: 0
  LOWER_LATENCY_THRESHOLD: 3
  UPPER_LATENCY_THRESHOLD: 6
  INIT_RESOURCE_LOAD: 0.9 
  NUMBER_OF_VIDEOS: 1

HMDS:
  LOWER_LATENCY_THRESHOLD: 4
  UPPER_LATENCY_THRESHOLD: 7

# ABS profile settings should match the latency thresholds specified here
SERVICES:
  VIDEO_RESOLUTION:
    LATENCY_THRESOLDS:
      8k: 3.5
      4k: 4
      2k: 4.5

